### ISSUE TITLE
SVG Edit Shapes doesn't work

### ISSUE THREAD

**Issue by nicolasd** [jarek-foksa/path-data-polyfill.js#1]
With the polyfill extension, SVG Edit doesn't work with shapes lib.

For example, choose the smiley, and try to draw this on the page. 

It will blink and resize the smiley badly
![svgedit](https://cloud.githubusercontent.com/assets/459201/10965169/795c7b52-83ab-11e5-8b4c-5d051f0a0ad7.png)

**Comment by jarek-foksa** [comment]
Where can I find the SVG Edit source code that was ported to the new API? The smiley shape is parsed correctly by the polyfill.

**Comment by progers** [comment]
I think nicolasd filed this against the wrong repo. This was meant for https://github.com/progers/pathseg. I've fixed this issue and updated the svg-edit pull request.

This issue can be closed.
