### ISSUE TITLE
Invariant results principle is violated.

### ISSUE THREAD

**Issue by ievgennaida** [jarek-foksa/path-data-polyfill.js#12]
Looks like even default call to the method is normalizing data.
The code below is describing the problem:

```    const el: any = document.createElementNS("http://www.w3.org/2000/svg", "path");
    el.setAttribute("d", "M 10 10 l 10 10 10 10");
    const el2: any = document.createElementNS("http://www.w3.org/2000/svg", "path");
    el2.setPathData(el.getPathData());
    let same = el2.getAttribute('d') == el.getAttribute('d');```

first call of el.getPathData() will return:
M 10 10
l 10 10 
l 10 10

while expected results:
M 10 10
l 10 10 10 10

For some tools changes in a path, nodes might be crucial.
I assume that default returned data for a polyfill should not be normalized.

**Comment by jarek-foksa** [comment]
element.getPathData() in your example is not performing normalization as defined by the spec, it is only expanding the shorthand notation (i.e. "M 10 10 l 10 10 10 10" -> "M 10 10 l 10 10 l 10 10").

**Comment by ievgennaida** [comment]
Yes, but expanding is also violates get and set. so initial results are not preserved. I dont think that browser implementation will do any expanding, usually it returns everything on the same way as it was defined.

**Comment by jarek-foksa** [comment]
I just checked the spec and it states clearly that `getPathData()` should return `sequence<SVGPathSegment>`. Since `M 10 10 l 10 10 10 10` represents three segments, the output of element.getPathData() should be an array containing one "M" segment and two "l" segments.

**Comment by ievgennaida** [comment]
From the grammar, it does not look like that but it's better than to rise a question to make this statement 100% clear in the documentation. 
https://github.com/w3c/svgwg/issues/789
In any case thanks for the quick reply!
