### ISSUE TITLE
WHY ??

### ISSUE THREAD

**Issue by sysmaya** [jarek-foksa/path-data-polyfill.js#16]
segmentsX is assumed to be a copy of Segments.
Then I modify Segments......
Ouch.. It turns out that the copy was also magically modified...

```
var pathEditNodes = document.getElementById("rect-275700788");
var segments = pathEditNodes.getPathData({normalize: true});
var segmentsx=segments;

console.log(segments);
console.log(segmentsx);

segments[0]['values'][0]=0;
segments[0]['values'][1]=1;

console.log(segments);
console.log(segmentsx);
```

It turns out that all the modifications made in the segments variable, also happen in the copy variable. Why??
So how am I supposed to get an original copy of the path returned by getPathData()?

**Comment by jarek-foksa** [comment]
This is basically how JavaScript works, please read https://javascript.info/object-copy for further explanation.
