### ISSUE TITLE
Why not use SVGPathSegment constructor instead of plain object ?

### ISSUE THREAD

**Issue by cuixiping** [jarek-foksa/path-data-polyfill.js#3]
Why not define SVGPathSegment constructor and use `new SVGPathSegment(type,values)` instead of plain object `{type:type,values:values}`  
SVG Paths spec: [7.1. Interface SVGPathSegment](https://svgwg.org/specs/paths/#InterfaceSVGPathSegment)

**Comment by jarek-foksa** [comment]
According to the spec SVGPathSegment is a [NoInterfaceObject](https://www.w3.org/TR/WebIDL/#NoInterfaceObject). If I understand the WebIDL syntax correctly, this means that the interface should be exposed as a plain JS object.
