### ISSUE TITLE
howto

### ISSUE THREAD

**Issue by pfx81** [jarek-foksa/path-data-polyfill.js#4]
Hello,
I am a beginner
how to apply the polyfill
I put the polyfill in my html containing my svg with a path #p1
var p1 = document.getElementById("p1");
var pathdata = p1.getPathData();
Uncaught TypeError: t.getPathData is not a function
I need a little help ...
Thanks

**Comment by jarek-foksa** [comment]
Could you please create a demo on jsfiddle.net demonstrating this issue? The polyfill does not rely on any third party module loaders or libraries, it should just work after you put it between `<script></script>` tags.

**Comment by pfx81** [comment]
I have no jsfiddel account.
Here's how I try to use your polyfill.
I just did a test page that you can inspect : 

thank you

**Comment by jarek-foksa** [comment]
Polyfill does not work because you are embedding the SVG document using `<object></object>` tags. You must use inline `<svg>` tags like this:

``` html
<!doctype html>
<html>
  <head>
    <script src="http://viasvt.fr/test-path-data/code/path-data-polyfill.js"></script>
    <script>
     window.addEventListener("load", (event) => {
       console.log("pathData", document.querySelector("path").getPathData());
     });
    </script>
  </head>
  <body>
    <svg viewBox="0 0 500 500">
      <path d="M 0 0 L 100 100 L 200 200"></path>
    </svg>
  </body>
</html>
```

**Comment by pfx81** [comment]
yes
thank you
