### ISSUE TITLE
example usage

### ISSUE THREAD

**Issue by pp05** [jarek-foksa/path-data-polyfill.js#5]
Hi..
Could anyone give a sample usage of these APIs, I am especially interested in the setPathData() ?
The svg 2.0 spec which specifies these new APIs also seems to be in a draft version at the moment so we are not getting a complete picture of the usage of these APIs especially what parameters it is expecting.

Thanks in advance.

**Comment by jarek-foksa** [comment]
I added several examples to the README.md file.
