### ISSUE TITLE
Syntax error: sample code in README

### ISSUE THREAD

**Issue by anseki** [jarek-foksa/path-data-polyfill.js#6]
Hi, thank you for your very useful polyfill.
Second sample code ("Create a triangle path") in README doesn't seem to work by syntax error.

``` js
    { type: "L", values: [x + width, y + height],
    { type: "L", values: [x, y + height],
```

There are not close-parentheses `}` at the right of `height]`.

**Comment by jarek-foksa** [comment]
Thanks, I added missing brackets.
