### ISSUE TITLE
IE compatibility?

### ISSUE THREAD

**Issue by TheRossman** [jarek-foksa/path-data-polyfill.js#9]
G'day, I tried this polyfill and it worked great in chrome but did not seem to work in PhantomJS or IE11 - two environments we need to ensure our unit tests run in.  Is this polyfill intended only to support Chrome?  Thank you!

**Comment by jarek-foksa** [comment]
Have you tried using `path-data-polyfill.es5.js`? Unlike `path-data-polyfill.js` it does not rely on the newly introduced ECMAScript features.

**Comment by TheRossman** [comment]
Thanks for your reply, I hadn't tried that yet, my mistake!  I'll give 'er a whirl right now!

Cheers!

**Comment by TheRossman** [comment]
The ES5 version still doesn't work in IE and seems like it also doesn't work in Chrome.  Hmmm.

**Comment by jarek-foksa** [comment]
I haven't tested the polyfill on IE myself, but I recall other users reporting it was working fine. Are there any errors printed in the console?

**Comment by TheRossman** [comment]
I get a "TypeError: Object doesn't support property or method 'getPathData'" in IE11.

It I log out what I'm trying to access, it is indeed a path element.  Not sure what's going on  :(

**Comment by jarek-foksa** [comment]
Are you getting the same error on Chrome? Are you sure you are loading the polyfill before executing any other scripts on the page?

**Comment by TheRossman** [comment]
Dude sorry please disregard my last comment, the ES5 version it working in IE, Chrome, and PhantomJS, I just made a typo!!  Thanks for replying nonetheless and sorry to be a bother!
